feat(debian): allow syncing only certain builds when testing apt
sync-releases-to-apt copies quick-lint-js releases into the apt pool.
Make it possible to opt out of this behavior in --testing mode with
--no-releases. This can speed up syncing, and can also make the
repository smaller and easier to debug.

diff --git a/dist/debian/sync-releases-to-apt b/dist/debian/sync-releases-to-apt
--- a/dist/debian/sync-releases-to-apt
+++ b/dist/debian/sync-releases-to-apt
@@ -17,6 +17,7 @@ apt_suite=experimental
 
 testing=0
 extra_builds=()
+sync_releases=1
 
 clean_up() {
   if [ -e "${ssh_control_socket:-}" ]; then
@@ -36,6 +37,8 @@ parse_args() {
   while [ "${#}" -gt 0 ]; do
     case "${1}" in
       --testing) testing=1 ;;
+
+      --no-releases) sync_releases=0 ;;
 
       +([0-9a-f]))
         if [ "${#1}" -ne 40 ]; then
@@ -63,6 +66,10 @@ main() {
     printf 'error: extra builds are only allowed with --testing\n' >&2
     exit 1
   fi
+  if [ "${sync_releases}" -eq 0 ] && [ "${testing}" -eq 0 ]; then
+    printf 'error: --no-releases is only allowed with --testing\n' >&2
+    exit 1
+  fi
 
   # Speed up repeated SSH/SCP commands by reusing a single TCP connection to the
   # server.
@@ -82,21 +89,24 @@ main() {
 copy_releases_to_debian_pool() {
   printf 'Populating Debian pool from releases ...\n' >&2
 
-  ssh "${ssh_args[@]}" "${ssh_host}" -- bash -s "${remote_builds_root}" "${remote_releases_root}" "${remote_debian_root}" "${extra_builds[@]:+${extra_builds[@]}}" <<'EOF'
+  ssh "${ssh_args[@]}" "${ssh_host}" -- bash -s "${remote_builds_root}" "${remote_releases_root}" "${remote_debian_root}" "${sync_releases}" "${extra_builds[@]:+${extra_builds[@]}}" <<'EOF'
     set -e
     set -u
 
     builds_root="${1}"
     releases_root="${2}"
     debian_root="${3}"
-    shift 3
+    sync_releases="${4}"
+    shift 4
     extra_builds=("${@}")
 
     mkdir -p "${debian_root}/pool/"
-    for release_path in "${releases_root}"/[0-9]*; do
-      release="$(basename "${release_path}")"
-      rsync -a "${release_path}/debian/" "${debian_root}/pool/${release}/"
-    done
+    if [ "${sync_releases}" -ne 0 ]; then
+      for release_path in "${releases_root}"/[0-9]*; do
+        release="$(basename "${release_path}")"
+        rsync -a "${release_path}/debian/" "${debian_root}/pool/${release}/"
+      done
+    fi
     for extra_build in "${extra_builds[@]:+${extra_builds[@]}}"; do
       rsync -a "${builds_root}/${extra_build}/debian/" "${debian_root}/pool/${extra_build}/"
     done
