fix crashes due to command not found 127

diff --git a/tools/format b/tools/format
--- a/tools/format
+++ b/tools/format
@@ -10,9 +10,11 @@ set -u
 cd "$(dirname "${0}")/.."
 source tools/files.sh
 
-clang_format_version="$(clang-format --version 2>/dev/null)"
+clang_format_version="$(clang-format --version 2>/dev/null || :)" 
 
-if [[ ${clang_format_version} != *"version 9"* ]]; then
+if [[ ${clang_format_version} = '' ]]; then
+  printf 'warning: clang-format is not installed. Version 9.0.x is required.\n' >&2 
+elif [[ ${clang_format_version} != *"version 9"* ]]; then
   printf 'warning: quick-lint-js is formatted using the clang-format tool version 9.0.x and you are using %s\n' "$clang_format_version" >&2 
 fi
 
diff --git a/tools/update-translator-sources b/tools/update-translator-sources
--- a/tools/update-translator-sources
+++ b/tools/update-translator-sources
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 # Copyright (C) 2020  Matthew "strager" Glazar
 # See end of file for extended copyright information.
@@ -16,18 +16,16 @@ main() {
 }
 
 check_dependencies() {
-  go_version=`go version | { read _ _ v _; echo ${v#go}; }`
+  go_version=`go version 2>/dev/null | { read _ _ v _; echo ${v#go}; }`
   min_go_version="1.16"
 
-  if [ "$(printf '%s\n' "$min_go_version" "$go_version" | sort -V | head -n1)" = "$go_version" ]; then 
+  if [ "$go_version" = "" ]; then 
+    printf 'warning: Go version %s or above required.\n' "$min_go_version" >&2 
+  elif [ "$(printf '%s\n' "$min_go_version" "$go_version" | sort -V | head -n1)" = "$go_version" ]; then 
     printf 'warning: Go version %s or above required. You are using version %s\n' "$min_go_version" "$go_version" >&2 
   fi
 
-  xgettext_version="$(xgettext -V 2>/dev/null)"
-
-  if [[ ${xgettext_version} != "xgettext "* ]]; then
-    printf 'warning: xgettext is required\n'>&2 
-  fi
+  xgettext_version="$(xgettext -V 2>/dev/null)" || printf 'warning: xgettext is required\n'
 }
 
 update_template_file() {
