refactor(tools): rewrite compile-translations.go in C++
Rewrite the compile-translations script from Go to C++.

There is an important difference between the Go and C++ versions: The Go
version used GNU gettext tools to convert the .po file into .mo files,
then it parsed the .mo files. The C++ version reads .po files directly.
Removing the dependency on GNU gettext (and the Go compiler) will let us
integrate compile-translations into the CMake build system in the
future.

diff --git a/tools/update-translator-sources b/tools/update-translator-sources
--- a/tools/update-translator-sources
+++ b/tools/update-translator-sources
@@ -12,23 +12,23 @@ main() {
   check_dependencies
   update_template_file
   update_translation_files
-  go run ./tools/compile-translations.go
+  ./build/quick-lint-js-compile-translations \
+    --output-translation-table-h src/quick-lint-js/i18n/translation-table-generated.h \
+    --output-translation-table-cpp src/quick-lint-js/i18n/translation-table-generated.cpp \
+    --output-translation-table-test test/quick-lint-js/test-translation-table-generated.h \
+    --po-template po/messages.pot \
+    po/*.po
 }
 
 check_dependencies() {
-  go_version=`go version 2>/dev/null | { read _ _ v _; echo ${v#go}; }`
-  min_go_version="1.16"
-
-  if [ "$go_version" = "" ]; then 
-    printf 'warning: Go version %s or above required.\n' "$min_go_version" >&2 
-  elif [ "$(printf '%s\n' "$min_go_version" "$go_version" | sort -V | head -n1)" = "$go_version" ]; then 
-    printf 'warning: Go version %s or above required. You are using version %s\n' "$min_go_version" "$go_version" >&2 
-  fi
-
   xgettext_version="$(xgettext -V 2>/dev/null)" || printf 'warning: xgettext is required\n'
 
   if ! [ -x ./build/quick-lint-js-extract-translatable-strings ]; then
       printf "error: missing build/quick-lint-js-extract-translatable-strings (compile it with 'ninja -C build quick-lint-js-extract-translatable-strings')\n" 2>&1
+      exit 1
+  fi
+  if ! [ -x ./build/quick-lint-js-compile-translations ]; then
+      printf "error: missing build/quick-lint-js-compile-translations (compile it with 'ninja -C build quick-lint-js-compile-translations')\n" 2>&1
       exit 1
   fi
 }
