Check go version and xgettext
Implements #833

diff --git a/tools/update-translator-sources b/tools/update-translator-sources
--- a/tools/update-translator-sources
+++ b/tools/update-translator-sources
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
 # Copyright (C) 2020  Matthew "strager" Glazar
 # See end of file for extended copyright information.
@@ -9,9 +9,23 @@ set -u
 cd "$(dirname "${0}")/.."
 
 main() {
+  check_dependencies
   update_template_file
   update_translation_files
   go run ./tools/compile-translations.go
+}
+
+check_dependencies() {
+  go_version=`go version 2>/dev/null | { read _ _ v _; echo ${v#go}; }`
+  min_go_version="1.16"
+
+  if [ "$go_version" = "" ]; then 
+    printf 'warning: Go version %s or above required.\n' "$min_go_version" >&2 
+  elif [ "$(printf '%s\n' "$min_go_version" "$go_version" | sort -V | head -n1)" = "$go_version" ]; then 
+    printf 'warning: Go version %s or above required. You are using version %s\n' "$min_go_version" "$go_version" >&2 
+  fi
+
+  xgettext_version="$(xgettext -V 2>/dev/null)" || printf 'warning: xgettext is required\n'
 }
 
 update_template_file() {
