Add missing copyrights; add tool to check

diff --git a/.github/workflows/check-copyright.yml b/.github/workflows/check-copyright.yml
--- a/.github/workflows/check-copyright.yml
+++ b/.github/workflows/check-copyright.yml
@@ -14,23 +14,26 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <https://www.gnu.org/licenses/>.
 
-set(QUICK_LINT_JS_CXX_COMPILER_OPTIONS "" CACHE STRING "")
-mark_as_advanced(QUICK_LINT_JS_CXX_COMPILER_OPTIONS)
+name: check copyright
+on:
+  push:
+  pull_request:
+    types: [opened, synchronize]
 
-function (quick_lint_js_add_executable TARGET)
-  add_executable(${ARGV})
-  target_compile_options(
-    "${TARGET}"
-    PRIVATE
-    "${QUICK_LINT_JS_CXX_COMPILER_OPTIONS}"
-  )
-endfunction ()
+jobs:
+  check_format:
+    name: check copyright
+    runs-on: ubuntu-latest
+    steps:
+      - if: ${{ github.event_name == 'push' }}
+        uses: actions/checkout@v2
+      - if: ${{ github.event_name == 'pull_request' }}
+        uses: actions/checkout@v2
+        with:
+          ref: ${{ github.event.pull_request.head.sha }}
 
-function (quick_lint_js_add_library TARGET)
-  add_library(${ARGV})
-  target_compile_options(
-    "${TARGET}"
-    PRIVATE
-    "${QUICK_LINT_JS_CXX_COMPILER_OPTIONS}"
-  )
-endfunction ()
+      - run: |
+          if ! ./tools/check-file-copyrights; then
+            printf '::error ::%s\n' 'Sources are missing copyright headers. Please add copyright headers for any new files you create.'
+            exit 1
+          fi
diff --git a/tools/check-file-copyrights b/tools/check-file-copyrights
--- a/tools/check-file-copyrights
+++ b/tools/check-file-copyrights
@@ -1,3 +1,5 @@
+#!/usr/bin/env bash
+
 # quick-lint-js finds bugs in JavaScript programs.
 # Copyright (C) 2020  Matthew Glazar
 #
@@ -14,23 +16,23 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <https://www.gnu.org/licenses/>.
 
-set(QUICK_LINT_JS_CXX_COMPILER_OPTIONS "" CACHE STRING "")
-mark_as_advanced(QUICK_LINT_JS_CXX_COMPILER_OPTIONS)
+set -e
+set -o pipefail
+set -u
 
-function (quick_lint_js_add_executable TARGET)
-  add_executable(${ARGV})
-  target_compile_options(
-    "${TARGET}"
-    PRIVATE
-    "${QUICK_LINT_JS_CXX_COMPILER_OPTIONS}"
-  )
-endfunction ()
+cd "$(dirname "${0}")/.."
+source tools/files.sh
 
-function (quick_lint_js_add_library TARGET)
-  add_library(${ARGV})
-  target_compile_options(
-    "${TARGET}"
-    PRIVATE
-    "${QUICK_LINT_JS_CXX_COMPILER_OPTIONS}"
-  )
-endfunction ()
+check_file_copyright_header() {
+  local file="${1}"
+  fgrep -q 'Copyright (C)' "${file}"
+}
+
+error=0
+for file in $(find_non_vendor_files | matching '(^CMakeLists\.txt|.bt|.c|.cmake|.cpp|.gperf|.h|.js|.mjs|.nix|.po|.pot|.py|.sh|.vim|.yaml)$'); do
+  if ! check_file_copyright_header "${file}"; then
+    printf 'error: file missing copyright: %s\n' "${file}"
+    error=1
+  fi
+done
+exit "${error}"
