feat(ci): test output of simple build
Make sure the simple build instructions produce a working executable.

diff --git a/.github/workflows/simple-build.yml b/.github/workflows/simple-build.yml
--- a/.github/workflows/simple-build.yml
+++ b/.github/workflows/simple-build.yml
@@ -32,6 +32,19 @@ jobs:
         # Keep in sync with "single-command build" in website/public/contribute/build-from-source/.
         run: '"${CXX}" ${CXXFLAGS} -o quick-lint-js -std=gnu++17 -I src -I vendor/boost -I vendor/simdjson/include -I vendor/simdjson/src -D_LIBCPP_HIDE_FROM_ABI_PER_TU_BY_DEFAULT=1 -D_LIBCPP_INLINE_VISIBILITY="__attribute__((internal_linkage))" src/quick-lint-js/*.cpp src/quick-lint-js/*/*.cpp vendor/boost/libs/container/src/*.cpp vendor/boost/libs/container/src/alloc_lib.c vendor/simdjson/src/simdjson.cpp -pthread'
 
+      - name: test
+        run: |
+          printf 'const x = 3;\nconst x = 4;\n' >errors.js
+          (
+            set +e
+            ./quick-lint-js errors.js
+            echo "STATUS=$?"
+          ) >output.txt 2>&1
+          cat output.txt
+
+          grep E0034 output.txt
+          grep STATUS=1 output.txt
+
 # quick-lint-js finds bugs in JavaScript programs.
 # Copyright (C) 2020  Matthew Glazar
 #
